project:
  type: website
  output-dir: docs

website:
  title: "Junior Sundar's Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ./blog/index.qmd
        text: Blog
      - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



